### ISSUE TITLE
Need restart after every step 

### ISSUE THREAD

**Issue by np252003** [ExoWorldsSpies/hops-3.0#1]
Need restart after every step 
Nikos Paschalis
![Screenshot 2021-01-31 204646](https://user-images.githubusercontent.com/78318718/106394487-83931280-6405-11eb-9570-c429aefc0175.png)

**Comment by atsiaras** [comment]
Could you please attach the information shown on the terminal?

**Comment by np252003** [comment]
Sorry, my bad...
Here it is
![Screenshot 2021-02-01 132928](https://user-images.githubusercontent.com/78318718/106453266-b08d0700-6491-11eb-8f52-1b1cb93ce028.png)

**Comment by atsiaras** [comment]
The issue has been resolved in the latest commit. Thanks again for the notice! Best, Angelos
